### ISSUE TITLE
VLC work via AA, but not "here we go" or "OSMAnd"

### ISSUE THREAD

**Issue by starbrights** [sn-00-x/aa4mg#1]
After enable in "Dev Settings" the point "Unknown apps" a few of my apps are listed in AA Lauchner, such as VLC, Signal, Whatsapp.
While VLC is very welcome - I miss alternative navigation apps as "here wego" or "OSMAnd".
(OSMAnd btw is installed via FDroid).
Nevertheless, the interesting thing is, that if I press Version (in AA) I can see OSMAnd~ and Here Wego listed (beside the above mentioned apps).
Is there a trick to get them working?

**Comment by starbrights** [comment]
Solved via https://github.com/UnlockAA/XPrivacyLuaHook

**Comment by Ex0danify** [comment]
Also wondering about this. I would really love to use osmAnd+ navigation with android auto, I'm currently running AA v.9.1.

I reply don't know how the link above could help me achiev my goal.

**Comment by Rikj000** [comment]
Thank you @Ex0danify, you beat me to the punch! :smile: 

The app has been renamed to XLauncher and got a new v2.0 release today,
which added a lot more functionality to it, you can find it here:
https://github.com/Rikj000/Android-Auto-XLauncher-Unlocked

It's also included in my new PR #10 

Hopefully soon it will ship together with the official `aa4mg`! :slightly_smiling_face: 
But for the time being you can already grab a pre-release from my fork:
https://github.com/Rikj000/AndroidAuto4MicroG/releases/tag/v0.5.0-a13

**Comment by answer35** [comment]
> Thank you @Ex0danify, you beat me to the punch! 😄
> 
> The app has been renamed to XLauncher and got a new v2.0.1 release today, which added a lot more functionality to it, you can find it here: https://github.com/Rikj000/Android-Auto-XLauncher-Unlocked
> 
> It's also included in my new PR #10
> 
> Hopefully soon it will ship together with the official `aa4mg`! 🙂 But for the time being you can already grab a pre-release from my fork: https://github.com/Rikj000/AndroidAuto4MicroG/releases/tag/v0.5.1-a13

I've followed the instructions on your repo to install XLauncher with KingInstaller but I'm still not able to see OsmAnd in my AA Apps. I've got LSPosed enabled, Shamiko is OK as well, module in LSPosed is enable with Android Auto and OsmAnd checked. I don't know what I missed
